# Keras
## Introducción
Keras es un API de alto nivel para redes neuronales, escrita en Python que es capaz de correr sobre TensorFlow, CNTK o Theano. Fue desarrollada con énfasis en habilitar experimentación rápida. Es recomendable el uso de Keras cuando se requiere de una libería de Deep Learning que:
- Permita el desarrollo de prototipos fácil y rápido (por medio de facilidad de uso, modularidad y extensibilidad).
- Soporte redes neuronales convolucionales (CNN) y redes neuronales recurrentes (RNN), así como combinaciones de ambas.
- Corra de forma natural en CPUs y GPUs.

Keras es compatible con Python 2.7-3.6.

[keras.io](https://keras.io) es el sitio principal del proyecto.

## Backend Keras y tf.keras
Se recomienda usar `tf.keras` a usuarios que usen Keras multi-backend con TensorFlow en TensorFlow 2.0 ya que `tf.keras` tiene mejor integración con las características de TensorFlow 2.0 (eager execution, soporte a distribución).

## Principios
- **Amigable**. El API está diseñado para personas, es consistente, reduce el número de pasos para casos de uso comunes. 
- **Modular**. Un modelo de deep learning consta de una secuencia o un grafo de módulos configurables que pueden ser conectados  con la menor cantidad de restricciones. Las capas de las redes neuronales, las funciones de costo, los optimizadores, esqueasm de inicialización, funciones de activación y esquemas de regularización son módulos independientes que pueden combinarse para crear nuevos modelos.
- **Extensible**. Es posible añadir módulos nuevos
- **Trabaja con Python**. No requiere de archivos de configuración de modelos. Los modelos se describen en Python, que es compacto, fácil de depurar y facilita la extensibilidad.

## Estructuras de datos
La estructura central de Keras es un modelo, que representa una forma de organizar capas. `Sequential` representa al modelo más simple, una pila linear de capas. El **Functional API**, por medio de `Model` permite crear arquitecturas más complejas por medio de un grafo arbitrario de capas.

In [6]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as k
#from tensorflow import keras

## Carga y preprocesamiento de datos
Las redes neuronales no procesan datos crudos como archivos de texto, imágenes codificadas en JPEG y otros formatos, o archivos CSV. Procesan representaciones vectorizadas y estandarizadas.
* Los archivos de texto necesitan ser leidos a tensores de sequencias de caracteres, divididos en palabrsa. Las palabras necesitan ser indexadas y convertidas a tensores de enteros.
* Las imágenes necesitan ser leídas y decodificadas en tensores de imágenes, convertidas a punto flotante y normalizados a valores pequeños (generalmente entre 0 y 1).
* Los datos CSV necesitan ser leídos, con características numéricas convertidas a tensores de punto flotante y características categóricas indexadas y convertidas a tensores enteros. Cada característica necesita ser normalizada con media cero y variación unitaria.

In [7]:
import pathlib
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file(origin=dataset_url,
                                   fname='flower_photos',
                                   untar=True)
data_dir = pathlib.Path(data_dir)

In [8]:
image_count = len(list(data_dir.glob('*/*.jpg')))
print(image_count)

3670


In [9]:
#Obtener un dataset etiquetado de imágenes en disco
# Create a dataset.
image_dataset = k.preprocessing.image_dataset_from_directory(
  data_dir, batch_size=32, image_size=(180, 180))

# For demonstration, iterate over the batches yielded by the dataset.
for data, labels in image_dataset:
   print(data.shape)  # (64, 200, 200, 3)
   print(data.dtype)  # float32
   print(labels.shape)  # (64,)
   print(labels.dtype)  # int32

Found 3670 files belonging to 5 classes.


2022-03-22 02:06:29.514353: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-03-22 02:06:29.531405: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-22 02:06:29.534601: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-03-22 02:06:30.083236: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-03-22 02:06:30.084742: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2593905000 Hz


(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32,)
<dtype: 'int32'>
(32, 180, 180, 3)
<dtype: 'float32'>
(32

In [4]:
!mkdir ./datasets
!curl -O https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -xf aclImdb_v1.tar.gz --directory ./datasets/

mkdir: cannot create directory ‘./datasets’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.2M  100 80.2M    0     0  17.9M      0  0:00:04  0:00:04 --:--:-- 17.9M


In [13]:
#Obtener un dataset etiquetado de archivos de texto en disco
text_dataset = k.preprocessing.text_dataset_from_directory(
  './datasets/aclImdb/train', batch_size=64)

# For demonstration, iterate over the batches yielded by the dataset.
for text_batch, label_batch in text_dataset.take(1):
    for i in range(5):
        print(text_batch.numpy()[i])
        print(label_batch.numpy()[i])

Found 75000 files belonging to 3 classes.
b'This is the kind of film that, if it were made today, it would probably star Sandra Bullock and Hugh Grant; actually, now that I think about it, this one is quite liable to be remade one day. It\'s pleasant, but with no depth whatsoever. It suffers from the almost fatal miscasting of James Stewart in a role he is about 20 years too old for, and as a result there is no chemistry between him and the beautiful Kim Novak. Ernie Kovacs, in the small supporting role of an aspiring writer, is the only actor in the film whose performance approaches what you might call "wit". (**1/2)'
1
b"I've seen hundreds of films at the theater and this was one of only two during which I actually fell asleep. Steve Martin and Bill Murray, along with the Dentist song, try to salvage an otherwise slow uninteresting film. In my book, this is one where the original was more enjoyable."
2
b'Fairly interesting exploitation flick in black and white written by David F. Fri

## Preprocesamiento de datos en Keras
* Generar tokens de secuencias de caracteres, posteriormente índices de tokens.
* Normalizar características.
* Reescalar los datos a valores pequeños (media cero y variación unitaria o datos en el rango [0, 1]).

Keras permite realizar el preprocesamiento de datos como parte del modelo.

In [14]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Example training data, of dtype `string`.
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample."]])

# Create a TextVectorization layer instance. It can be configured to either
# return integer token indices, or a dense token representation (e.g. multi-hot
# or TF-IDF). The text standardization and text splitting algorithms are fully
# configurable.
vectorizer = TextVectorization(output_mode="int")

# Calling `adapt` on an array or dataset makes the layer generate a vocabulary
# index for the data, which can then be reused when seeing new data.
vectorizer.adapt(training_data)

# After calling adapt, the layer is able to encode any n-gram it has seen before
# in the `adapt()` data. Unknown n-grams are encoded via an "out-of-vocabulary"
# token.
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[4 5 2 9 3]
 [7 6 2 8 3]], shape=(2, 5), dtype=int64)


In [15]:
# Convertir secuencias de caracteres a bigrams de tipo one-hot encoding
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Example training data, of dtype `string`.
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample."]])

# Create a TextVectorization layer instance. It can be configured to either
# return integer token indices, or a dense token representation (e.g. multi-hot
# or TF-IDF). The text standardization and text splitting algorithms are fully
# configurable.
vectorizer = TextVectorization(output_mode="binary", ngrams=2)

# Calling `adapt` on an array or dataset makes the layer generate a vocabulary
# index for the data, which can then be reused when seeing new data.
vectorizer.adapt(training_data)

# After calling adapt, the layer is able to encode any n-gram it has seen before
# in the `adapt()` data. Unknown n-grams are encoded via an "out-of-vocabulary"
# token.
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]], shape=(2, 17), dtype=float32)


In [16]:
# Normalización de características
from tensorflow.keras.layers.experimental.preprocessing import Normalization

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

normalizer = Normalization(axis=-1)
normalizer.adapt(training_data)

normalized_data = normalizer(training_data)
print("var: %.4f" % np.var(normalized_data))
print("mean: %.4f" % np.mean(normalized_data))

var: 1.0000
mean: -0.0000


In [34]:
# Cambiar la escala, centrar y recortar imágenes
from tensorflow.keras.layers.experimental.preprocessing import CenterCrop
from tensorflow.keras.layers.experimental.preprocessing import Rescaling

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

cropper = CenterCrop(height=150, width=150)
scaler = Rescaling(scale=1.0 / 255)

output_data = scaler(cropper(training_data))
print("shape:", output_data.shape)
print("min:", np.min(output_data))
print("max:", np.max(output_data))

shape: (64, 150, 150, 3)
min: 0.0
max: 1.0


## Creación de instancia de modelo

En cuanto se haya definido el grafo de capas que convierte las entradas en salidas, es posible instanciar el objeto Model().
```
model = keras.Model(inputs=inputs, outputs=outputs)
```
Es posible invocar el modelo en subconjuntos de datos

In [ ]:
model = k.Model(inputs=inputs, outputs=outputs)

In [ ]:
data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")
processed_data = model(data)
print(processed_data.shape)

NameError: name 'model' is not defined

Es posible desplegar un resumen de las trasnformaciones de datos en cada etapa. Esto es útil para depuración.
```
model.summary()
```

## Entrenamiento de modelos con fit()
Hasta este punto:
* Los datos se encuentran preparados.
* Se ha definido un modelo para ajustar los datos.
El siguiente paso es entrenar el modelo con los datos. La clase Model cuenta con un ciclo de entrenamiento, el método fit().

Antes de invocar fit() se debe especificar un optimizador y una función de pérdida. Este es el paso compile()


In [35]:
model.compile(optimizer=keras.optimizers.RMSprop(learning_rate=1e-3),
              loss=keras.losses.CategoricalCrossentropy())

NameError: name 'model' is not defined

La función de pérdida y el optimizador puede ser especificada por medio de sus identificadores como cadenas de caracteres

In [ ]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

Cuando el modelo está compilado, es posible comenzar a ajustar el modelo a los datos.

In [ ]:
model.fit(numpy_array_of_samples, numpy_array_of_labels,
          batch_size=32, epochs=10)

In [ ]:
También es posible especificar el tamaño del batch y el número de épocas (iteraciones sobre los datos).

In [ ]:
model.fit(dataset_of_samples_and_labels, epochs=10)