# NuPy (Numerical Python)
## Introducción
### ¿Qué es?
NumPy es el paquete fundamental para cómputo científico en Python. Es una librería que provee de un objeto tipo arreglo multidimensional y varios objetos derivados tales como arreglos enmascarados y matrices, así como rutinas para operaciones ágiles con arreglos, incluyendo matemáticas, lógicas, manipulación de formas, ordenamiento, selección, I/O, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación de valores aleatorios y más.

### Beneficios
* La estructura de datos ndarray es más eficiente para almacenar y manejar datos numéricos, en comparación con las estructuras de la distribución estándar de Python.
* Las librerías escritas en lenguajes de bajo nivel -tales como C- pueden operar con datos almacenados en el ndarray de Numpy sin tener que copiar datos.

## Estructura de datos (ndarray)
### Concepto
Arreglo multidimensional rápido y eficiente respecto al almacenamiento, el cual puede funcionar para almacenar datos homogéneos. Provee de operaciones aritméticas con soporte a vectorización.

### Crear ndarray

In [3]:
import numpy as np
#Crear un ndarray
r = range(10)
np.array(r)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Crer NdArray personalizados

In [4]:
#Arreglo de una dimensión con 10 elementos con valor 0.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Arreglo de dos dimensiones con 6 elementos con valor 1.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# Arreglo de dos dimensiones con valores aleatorios
randarray = np.random.randn(2,3)
randarray

array([[ 1.20390287, -0.64943215, -0.11515287],
       [ 0.90299308,  1.53758089,  0.26891018]])

In [8]:
Arreglo de tres dimensiones con valores no inicializados
np.empty((3,4,5))
#La función empty no garantiza regresar valores cero

array([[[ 3.68402372e-043,  6.38796479e+029,  1.82861333e-094,
          8.78421503e+247,  2.34896698e+251],
        [ 9.52023510e+150,  2.51318105e+088,  1.81786175e+185,
          2.42766859e-154,  1.35237560e+045],
        [ 2.97034456e+222,  2.34785930e+251,  4.93949479e+111,
          1.13557120e-153,  1.27734658e-152],
        [ 3.89740696e+160,  1.28013918e-152,  4.19334307e+228,
          2.44088558e-154,  1.57999620e-313]],

       [[ 2.54679929e+059,  1.24019659e+151,  2.74590881e+030,
          9.38142371e-082,  5.36530393e-080],
        [ 3.98386110e+252,  4.08828928e+233,  2.11263694e+035,
          9.08625603e+044,  2.07591286e+243],
        [ 6.86592573e+246,  2.91300382e+256,  4.76688569e+180,
          1.75393304e-321,  3.80261646e-311],
        [ 4.57509083e-308,  2.54266473e-191,  4.89467838e-296,
          2.13450446e-287,  2.79273096e-287]],

       [[ 3.32653142e-111,  6.59046452e-244,  3.70188797e-313,
          3.16056534e+233, -3.84192429e+125],
        [ 9.882

In [12]:
# Versión de ndarray de la función range de Python
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
# Obtener el número de dimensiones
somearray = np.empty((3,4,5))
somearray.shape

(3, 4, 5)

In [14]:
# Obtener el tipo de datos
somearray.dtype

dtype('float64')

In [17]:
# Casting explícito
somearray2 = somearray.astype(np.int32)
somearray2.dtype
somearray2

array([[[          0, -2147483648,           0, -2147483648,
         -2147483648],
        [-2147483648, -2147483648, -2147483648,           0,
         -2147483648],
        [-2147483648, -2147483648, -2147483648,           0,
                   0],
        [-2147483648,           0, -2147483648,           0,
                   0]],

       [[-2147483648, -2147483648, -2147483648,           0,
                   0],
        [-2147483648, -2147483648, -2147483648, -2147483648,
         -2147483648],
        [-2147483648, -2147483648, -2147483648,           0,
                   0],
        [          0,           0,           0,           0,
                   0]],

       [[          0,           0,           0, -2147483648,
         -2147483648],
        [          0,           0,           0, -2147483648,
                   0],
        [-2147483648, -2147483648, -2147483648, -2147483648,
         -2147483648],
        [          0,           0,           0, -2147483648,
         -2

## Slicing (índices y subconjuntos)

* Slicing provee de una vista de los datos originales. No se copian los datos. Cualquier modificación a la vista se verá reflejada en los datos originales.
* Es posible llevar a cabo una copia de los datos por medio de la función copy.

In [19]:
#Copia explícita
somearray[2:6].copy

<function ndarray.copy>

In [20]:
#El indexado de arreglos multidimensionales puede tener dos formas
somearray[0][0][0]

3.684023722016545e-43

In [21]:
somearray[0,0,0]

3.684023722016545e-43

## Transposición
Una forma especial de cambio de forma que regresa una vsita de los datos, no copia.

In [30]:
transposeme = np.random.randn(3,4)
transposeme

array([[-0.87746186, -0.09040581,  0.46295046, -1.11725789],
       [ 0.04334713, -2.01723401,  0.58479402, -1.06598404],
       [ 1.07309608,  0.84913546,  0.33648294, -1.77776792]])

In [31]:
transposeme.T

array([[-0.87746186,  0.04334713,  1.07309608],
       [-0.09040581, -2.01723401,  0.84913546],
       [ 0.46295046,  0.58479402,  0.33648294],
       [-1.11725789, -1.06598404, -1.77776792]])

In [32]:
transposeme.transpose()

array([[-0.87746186,  0.04334713,  1.07309608],
       [-0.09040581, -2.01723401,  0.84913546],
       [ 0.46295046,  0.58479402,  0.33648294],
       [-1.11725789, -1.06598404, -1.77776792]])

In [33]:
transposeme.swapaxes(0,1)

array([[-0.87746186,  0.04334713,  1.07309608],
       [-0.09040581, -2.01723401,  0.84913546],
       [ 0.46295046,  0.58479402,  0.33648294],
       [-1.11725789, -1.06598404, -1.77776792]])

## Envolventes (wrappers) para funciones de Python que procesan datos escalares

In [44]:
wrapme = np.random.rand(4,3)
wrapme

array([[0.80947634, 0.73471094, 0.0556154 ],
       [0.99878509, 0.17770948, 0.52772364],
       [0.51583496, 0.00792215, 0.4038782 ],
       [0.08159909, 0.86890365, 0.33085085]])

In [39]:
import math
math.sqrt(9.99)

3.1606961258558215

In [40]:
math.sqrt(wrapme) # Produce error de tiempo de ejecución

TypeError: only size-1 arrays can be converted to Python scalars

In [45]:
np.sqrt(wrapme)

array([[0.89970903, 0.85715281, 0.23582917],
       [0.99939236, 0.42155602, 0.72644589],
       [0.71821652, 0.08900647, 0.63551412],
       [0.28565555, 0.93215001, 0.57519636]])

## Broadcasting
Es posible crear expresiones en Python donde se combinen variables de múltiples dimensiones con operadores y variables escalares

### Operaciones aritméticas con un arreglo numpy y valores escalares

In [60]:

bcast1 = np.array(range(4))
bcast1 = bcast1.reshape(-1,1)
bcast1 + 100


array([[100],
       [101],
       [102],
       [103]])

In [65]:
bcast1 - 1

array([[-1],
       [ 0],
       [ 1],
       [ 2]])

In [66]:
bcast1 * 10

array([[ 0],
       [10],
       [20],
       [30]])

In [67]:
bcast1 / 2

array([[0. ],
       [0.5],
       [1. ],
       [1.5]])

In [68]:
bcast1

array([[0],
       [1],
       [2],
       [3]])

### Operaciones con matrices de distintas dimensiones en las que se aplica broadcasting para alinear las dimensiones de las matrices y admitir la operación

In [72]:
bcast2 = np.array(range(6)).reshape(2,3)
bcast2

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
bcast100 = np.array([100,100,100]).reshape(1,3)
bcast2 + bcast100

array([[100, 101, 102],
       [103, 104, 105]])

In [86]:
bcast3 = np.array(range(9)).reshape(3,-1)
bcast3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
bcast4 = bcast100.reshape(3,-1)
bcast4

array([[100],
       [100],
       [100]])

In [88]:
bcast3 + bcast4

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

### Producto dot
np.dot es el producto dot de dos matrices
https://en.wikipedia.org/wiki/Dot_product

|A B| (dot) |E F| = | A\*E+B\*G A\*F+B\*H |

|C D|  .....  |G H| = | C\*E+D\*G C\*F+D\*H |

In [95]:
mat1 = np.array(range(4)).reshape(2,-1)
mat1

array([[0, 1],
       [2, 3]])

In [96]:
mat2 = np.array([10,20,30,40]).reshape(2,-1)
mat2

array([[10, 20],
       [30, 40]])

In [97]:
np.dot(mat1,mat2)

array([[ 30,  40],
       [110, 160]])

In [98]:
#Multiplicación elemento-a-elemento de matrices
mat1*mat2

array([[  0,  20],
       [ 60, 120]])