# NuPy (Numerical Python)
## Introducción
### ¿Qué es?
NumPy es el paquete fundamental para cómputo científico en Python. Es una librería que provee de un objeto tipo arreglo multidimensional y varios objetos derivados tales como arreglos enmascarados y matrices, así como rutinas para operaciones ágiles con arreglos, incluyendo matemáticas, lógicas, manipulación de formas, ordenamiento, selección, I/O, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación de valores aleatorios y más.

### Beneficios
* La estructura de datos ndarray es más eficiente para almacenar y manejar datos numéricos, en comparación con las estructuras de la distribución estándar de Python.
* Las librerías escritas en lenguajes de bajo nivel -tales como C- pueden operar con datos almacenados en el ndarray de Numpy sin tener que copiar datos.

## Estructura de datos (ndarray)
### Concepto
Arreglo multidimensional rápido y eficiente respecto al almacenamiento, el cual puede funcionar para almacenar datos homogéneos. Provee de operaciones aritméticas con soporte a vectorización.

### Crear ndarray

In [2]:
import numpy as np
#Crear un ndarray
r = range(10)
np.array(r)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Crer NdArray personalizados

In [3]:
#Arreglo de una dimensión con 10 elementos con valor 0.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Arreglo de dos dimensiones con 6 elementos con valor 1.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Arreglo de dos dimensiones con valores aleatorios
randarray = np.random.randn(2,3)
randarray

array([[ 1.22821803, -1.03700657,  0.01553553],
       [ 1.17647568,  0.54810886,  0.69540176]])

In [7]:
#Arreglo de tres dimensiones con valores no inicializados
np.empty((3,4,5))
#La función empty no garantiza regresar valores cero

array([[[ 1.30257873e-311,  1.30255051e-311, -3.38460733e+125,
          4.24407456e-290,  2.71963326e-307],
        [ 1.33360320e+241,  3.98977649e-310,  1.17500849e-308,
          2.00543682e-303,  1.29711354e+219],
        [ 4.90385075e+252,  4.62485892e-303,  4.53595075e+223,
          6.86722001e+149,  3.50640140e+151],
        [ 3.01467454e+161, -2.12368096e+127,  2.56866385e+151,
          2.59345485e+161,  8.81952217e+199]],

       [[ 1.87239084e-311,  1.88743680e+007,  9.64347618e-313,
          2.83088498e-307,  1.30434835e+214],
        [ 4.65204814e+151,  6.70552254e-008,  2.71963326e-307,
          1.33360320e+241,  4.66839074e-313],
        [ 2.76187293e-306,  3.19125514e-241,  6.45658124e-111,
          2.05737730e-099,  1.89118984e+219],
        [ 1.87242432e-311,  1.93676345e-282,  1.89119590e+219,
          2.30955689e+161,  8.31833568e-273]],

       [[ 1.79209176e-313,  8.18434960e-085,  5.81821776e+180,
          3.66216743e-263,  1.10262801e+161],
        [ 2.142

In [8]:
# Versión de ndarray de la función range de Python
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
# Obtener el número de dimensiones
somearray = np.empty((3,4,5))
somearray.shape

(3, 4, 5)

In [11]:
# Obtener el tipo de datos
somearray.dtype

dtype('float64')

In [10]:
# Casting explícito
somearray2 = somearray.astype(np.int32)
somearray2.dtype
somearray2

array([[[          0,           0, -2147483648,           0,
                   0],
        [-2147483648,           0,           0,           0,
         -2147483648],
        [-2147483648,           0, -2147483648, -2147483648,
         -2147483648],
        [-2147483648, -2147483648, -2147483648, -2147483648,
         -2147483648]],

       [[          0,    18874368,           0,           0,
         -2147483648],
        [-2147483648,           0,           0, -2147483648,
                   0],
        [          0,           0,           0,           0,
         -2147483648],
        [          0,           0, -2147483648, -2147483648,
                   0]],

       [[          0,           0, -2147483648,           0,
         -2147483648],
        [          0,           0, -2147483648, -2147483648,
                   0],
        [          0, -2147483648,           0, -2147483648,
         -2147483648],
        [          0,           0,           0,           0,
           

## Slicing (índices y subconjuntos)

* Slicing provee de una vista de los datos originales. No se copian los datos. Cualquier modificación a la vista se verá reflejada en los datos originales.
* Es posible llevar a cabo una copia de los datos por medio de la función copy.

In [12]:
#Copia explícita
somearray[2:6].copy

<function ndarray.copy>

In [13]:
#El indexado de arreglos multidimensionales puede tener dos formas
somearray[0][0][0]

1.302578734001e-311

In [14]:
somearray[0,0,0]

1.302578734001e-311

## Transposición
Una forma especial de cambio de forma que regresa una vsita de los datos, no copia.

In [15]:
transposeme = np.random.randn(3,4)
transposeme

array([[-1.2286707 , -1.23662718, -1.88066463, -1.42548332],
       [ 0.0267331 ,  0.34001253,  0.96244233, -0.09632356],
       [ 2.08317824,  1.14760932,  1.50322482,  0.09191723]])

In [16]:
transposeme.T

array([[-1.2286707 ,  0.0267331 ,  2.08317824],
       [-1.23662718,  0.34001253,  1.14760932],
       [-1.88066463,  0.96244233,  1.50322482],
       [-1.42548332, -0.09632356,  0.09191723]])

In [17]:
transposeme.transpose()

array([[-1.2286707 ,  0.0267331 ,  2.08317824],
       [-1.23662718,  0.34001253,  1.14760932],
       [-1.88066463,  0.96244233,  1.50322482],
       [-1.42548332, -0.09632356,  0.09191723]])

In [18]:
transposeme.swapaxes(0,1)

array([[-1.2286707 ,  0.0267331 ,  2.08317824],
       [-1.23662718,  0.34001253,  1.14760932],
       [-1.88066463,  0.96244233,  1.50322482],
       [-1.42548332, -0.09632356,  0.09191723]])

## Envolventes (wrappers) para funciones de Python que procesan datos escalares

In [19]:
wrapme = np.random.rand(4,3)
wrapme

array([[0.51547347, 0.27741235, 0.83169035],
       [0.10722707, 0.09018416, 0.46820411],
       [0.01335365, 0.10169216, 0.74912919],
       [0.57976169, 0.45124001, 0.22481521]])

In [20]:
import math
math.sqrt(9.99)

3.1606961258558215

In [21]:
math.sqrt(wrapme) # Produce error de tiempo de ejecución

TypeError: only size-1 arrays can be converted to Python scalars

In [22]:
np.sqrt(wrapme)

array([[0.71796481, 0.52669948, 0.91197059],
       [0.32745544, 0.30030678, 0.68425442],
       [0.115558  , 0.31889208, 0.8655225 ],
       [0.76142083, 0.67174401, 0.47414683]])

## Broadcasting
Es posible crear expresiones en Python donde se combinen variables de múltiples dimensiones con operadores y variables escalares

### Operaciones aritméticas con un arreglo numpy y valores escalares

In [23]:

bcast1 = np.array(range(4))
bcast1 = bcast1.reshape(-1,1)
bcast1 + 100


array([[100],
       [101],
       [102],
       [103]])

In [24]:
bcast1 - 1

array([[-1],
       [ 0],
       [ 1],
       [ 2]])

In [25]:
bcast1 * 10

array([[ 0],
       [10],
       [20],
       [30]])

In [26]:
bcast1 / 2

array([[0. ],
       [0.5],
       [1. ],
       [1.5]])

In [27]:
bcast1

array([[0],
       [1],
       [2],
       [3]])

### Operaciones con matrices de distintas dimensiones en las que se aplica broadcasting para alinear las dimensiones de las matrices y admitir la operación

In [28]:
bcast2 = np.array(range(6)).reshape(2,3)
bcast2

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
bcast100 = np.array([100,100,100]).reshape(1,3)
bcast2 + bcast100

array([[100, 101, 102],
       [103, 104, 105]])

In [30]:
bcast3 = np.array(range(9)).reshape(3,-1)
bcast3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
bcast4 = bcast100.reshape(3,-1)
bcast4

array([[100],
       [100],
       [100]])

In [32]:
bcast3 + bcast4

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

### Producto dot
np.dot es el producto dot de dos matrices
https://en.wikipedia.org/wiki/Dot_product

|A B| (dot) |E F| = | A\*E+B\*G A\*F+B\*H |

|C D|  .....  |G H| = | C\*E+D\*G C\*F+D\*H |

In [33]:
mat1 = np.array(range(4)).reshape(2,-1)
mat1

array([[0, 1],
       [2, 3]])

In [34]:
mat2 = np.array([10,20,30,40]).reshape(2,-1)
mat2

array([[10, 20],
       [30, 40]])

In [35]:
np.dot(mat1,mat2)

array([[ 30,  40],
       [110, 160]])

In [36]:
#Multiplicación elemento-a-elemento de matrices
mat1*mat2

array([[  0,  20],
       [ 60, 120]])